name: Create and publish docker image

on: push

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        with:
          tagRegex: "(.*)"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image name
        run: |
          IMAGE_TAG=$GIT_TAG_NAME
          echo "DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/java-mike:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Build docker image
        run: >-
          docker build .
          --label "org.label-schema.vcs-ref=$GITHUB_SHA"
          --tag $DOCKER_IMAGE
      - run: docker push $DOCKER_IMAGE
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.4
        with:
          app_name: goldfish-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                    {
                      "name": "java-mike",
                      "image":{
                        "registry_type": "DOCKER_HUB",
                        "registry": "kmikaz",
                        "repository": "java-mike",
                        "tag": "$IMAGE_TAG"
                        },
                      },
                  ]'